
x-common-variables: &common-variables
  MONGODB_USERNAME: okteto
  MONGODB_PASSWORD: mongodb123
  MONGODB_DATABASE: okteto
  MONGODB_HOST: mongodb
  MONGODB_ROOT_PASSWORD: mongodb123root
  MONGODB_SYSTEM_LOG_VERBOSITY: 0
  MONGODB_DISABLE_SYSTEM_LOG: no
  MONGODB_ENABLE_IPV6: no
  MONGODB_ENABLE_DIRECTORY_PER_DB: no

services:

  movies:
    build: reverse-proxy
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    restart: always

  frontend:
    build: frontend
    ports:
      - 80
    volumes:
      - frontend:/src
    command: yarn start

  api:
    build: api
    environment:
      <<: *common-variables
    ports:
      - 8080
    volumes:
      - api:/usr/src/app
    command: yarn start
    depends_on:
      mongodb:
        condition: service_healthy

  init:
    build: api
    environment:
      <<: *common-variables
    command: yarn load
    restart: never
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: docker.io/bitnami/mongodb:4.0.12-debian-9-r43
    environment:
      <<: *common-variables
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
